<a href="https://colab.research.google.com/github/anaberereta-hue/Trabajos-Colab/blob/main/Semana13_Grafos_Rep_Clase_RealAnah%C3%AD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ejercicios de Implementación de Grafos

##Estructura de datos - P2467

Nombre: Anahí Real

Fecha: 09 de julio, 2026

# Matriz de Adyacencia

In [14]:
# Grafo ejemplo: A-B(2), A-C(5), B-C(1), B-D(4)
import numpy as np
# Vértices del grafo
vertices = ['A', 'B', 'C', 'D']
n = len(vertices)
# Mapeo de vértice a índice numérico
idx = {v: i for i, v in enumerate(vertices)}
# Crear matriz de adyacencia (inicializada con ceros)
adj = np.zeros((n, n), dtype=int)
# Definir las aristas con sus pesos
aristas = [('A','B',2),('A','C',5),
('B','C',1),('B','D',4)]
# Llenar la matriz de adyacencia
for u, v, w in aristas:
  adj[idx[u]][idx[v]] = w # Arista u -> v con peso w
  adj[idx[v]][idx[u]] = w # Arista v -> u con peso w (no dirigido)
print(adj)
# [[0 2 5 0]
# [2 0 1 4]
# [5 1 0 0]
# [0 4 0 0]]
# Verificar la existencia y peso de una arista (ej: A-B)
print(adj[idx['A']][idx['B']]) # → 2
# Encontrar los vecinos del vértice (ej: B)
vecinos_B = [vertices[j]
for j in range(n)
if adj[idx['B']][j] > 0]
print(vecinos_B) # → ['A', 'C', 'D']

[[0 2 5 0]
 [2 0 1 4]
 [5 1 0 0]
 [0 4 0 0]]
2
['A', 'C', 'D']


# Lista de Adyacencia

In [15]:
# Mismo grafo representado con lista de adyacencia usando un diccionario
from collections import defaultdict

class Grafo:
  # Inicializa el grafo
  def __init__(self, dirigido=False):
    self.adj = defaultdict(list) # Usa defaultdict para listas vacías por defecto
    self.dirigido = dirigido # Indica si el grafo es dirigido o no

  # Agrega una arista al grafo
  def agregar_arista(self, u, v, w=1):
    self.adj[u].append((v, w)) # Agrega (destino, peso) a la lista de origen
    if not self.dirigido:
      self.adj[v].append((u, w)) # Si no es dirigido, agrega también la arista inversa

  # Retorna los vecinos de un vértice
  def vecinos(self, v):
    return self.adj[v]

  # Verifica si existe una arista entre dos vértices
  def tiene_arista(self, u, v):
    # Comprueba si 'v' está en la lista de vecinos de 'u'
    return any(x == v for x, _ in self.adj[u])

# Uso de la clase Grafo
g = Grafo(dirigido=False)
# Aristas del grafo
for u, v, w in [('A','B',2),('A','C',5), ('B','C',1),('B','D',4)]:
  g.agregar_arista(u, v, w)

# Imprime la lista de adyacencia completa (como diccionario)
print(dict(g.adj))
# {'A':[('B',2),('C',5)],
# 'B':[('A',2),('C',1),('D',4)], ...}

# Obtiene y imprime los vecinos de 'B'
print(g.vecinos('B')) # [('A',2),('C',1),('D',4)]

# Verifica si existe la arista 'A'-'B'
print(g.tiene_arista('A','B'))

{'A': [('B', 2), ('C', 5)], 'B': [('A', 2), ('C', 1), ('D', 4)], 'C': [('A', 5), ('B', 1)], 'D': [('B', 4)]}
[('A', 2), ('C', 1), ('D', 4)]
True


#Conclusión

La matriz de adyacencia es una representación en forma de tabla ideal para grafos con muchas aristas o algoritmos que requieren verificar constantemente si dos vértices están conectados, operación que realiza en tiempo constante $O(1)$. Sin embargo, su principal desventaja es el alto consumo de memoria $O(V^2)$ y la ineficiencia para listar los vecinos de un nodo, ya que obliga a recorrer filas completas de tamaño $V$.

Por otro lado, la lista de adyacencia es la opción más eficiente y utilizada en el mundo real, especialmente para grafos con pocas aristas. Destaca por optimizar el espacio en memoria a $O(V + E)$ y permitir una iteración rápida sobre los vecinos de un vértice, su único punto débil es que verificar la existencia de una arista específica requiere recorrer la lista, tomando un tiempo proporcional al grado del vértice.